### ISSUE TITLE
pre-commit-terraform terraform_docs changes in v1.93+

### ISSUE THREAD

**Issue by MaxymVlasov** [terraform-ibm-modules/common-dev-assets#1030]
Just in case you plan to update to new versions of hook (1.93.0+)

You need to drop the template section to use the default one
https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets%2F.terraform-docs-config.yaml#L9-L12

Or run simple bash script from p.3 in https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_docs which will replace all comment ocurences

**Comment by ocofaigh** [comment]
We don't use the official `terraform_docs` pre commit hook - we have our own custom hook which uses terraform_docs directly. @akocbek can you confirm we have no action here?

**Comment by MaxymVlasov** [comment]
Ah, I see 
https://github.com/terraform-ibm-modules/common-dev-assets/blob/1cceed81d904a2923c2137499260320b0455b101/module-assets/.pre-commit-config.yaml#L149-L156

Super, one less case to cover for us :)
